// Product data for the store - Pakistani Fashion Collection
// All prices in PKR (Pakistani Rupees)

export const staticProducts = [
    // ===== WOOL WINTER SHAWLS =====
    {
        id: 1,
        name: "Wool Winter Shawl - Off White",
        description: "Stay warm in style with our Wool Winter Shawl. Soft, breathable, and beautifully crafted for cold days. Made from premium wool, it offers cozy warmth without bulk, perfect for layering over any outfit. Timeless, versatile, and effortlessly elegant.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-white.png",
        image_url: "/images/products/shawl-white.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 2,
        name: "Wool Winter Shawl - Beige",
        description: "Premium wool winter shawl in a sophisticated beige color. Features elegant embroidered borders and soft fringed edges. Perfect for formal occasions and everyday winter wear.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-beige.png",
        image_url: "/images/products/shawl-beige.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 3,
        name: "Wool Winter Shawl - Black",
        description: "Classic black wool winter shawl with timeless appeal. Crafted from premium wool with decorative border stitching. Adds a touch of elegance to any winter ensemble.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-black.png",
        image_url: "/images/products/shawl-black.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 4,
        name: "Wool Winter Shawl - Grey",
        description: "Elegant grey wool winter shawl for the modern wardrobe. Lightweight yet warm, with beautiful texture and fringed edges. Perfect for all winter occasions.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-grey.png",
        image_url: "/images/products/shawl-grey.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },
    {
        id: 5,
        name: "Wool Winter Shawl - Navy Blue",
        description: "Rich navy blue wool winter shawl with premium finish. Soft, breathable, and beautifully crafted for cold days. A versatile addition to your winter collection.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-navy.png",
        image_url: "/images/products/shawl-navy.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },
    {
        id: 6,
        name: "Wool Winter Shawl - Maroon",
        description: "Deep maroon wool winter shawl with traditional appeal. Features decorative border work and soft fringed edges. Perfect for formal winter occasions.",
        price: 3499,
        salePrice: 2999,
        sale_price: 2999,
        category: "shawl",
        image: "/images/products/shawl-maroon.png",
        image_url: "/images/products/shawl-maroon.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },
    {
        id: 7,
        name: "Kashmiri Embroidered Shawl",
        description: "Exquisite hand-embroidered Kashmiri shawl featuring intricate paisley patterns. Made from pure Pashmina wool for exceptional warmth. Perfect for weddings and formal occasions.",
        price: 5999,
        salePrice: 4999,
        sale_price: 4999,
        category: "shawl",
        image: "/images/products/shawl-kashmiri.png",
        image_url: "/images/products/shawl-kashmiri.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 8,
        name: "Pashmina Silk Shawl",
        description: "Fine Pashmina silk blend shawl with delicate embroidery. Lightweight, elegant and perfect for both casual and formal wear. A luxury addition to any wardrobe.",
        price: 6999,
        salePrice: 5499,
        sale_price: 5499,
        category: "shawl",
        image: "/images/products/shawl-pashmina.png",
        image_url: "/images/products/shawl-pashmina.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },

    // ===== MUFFLERS =====
    {
        id: 9,
        name: "Cashmere Wool Muffler",
        description: "Premium cashmere wool muffler with fringed edges. Ultra-soft and warm, perfect for cold winter mornings. Available in classic neutral colors.",
        price: 1999,
        salePrice: 1499,
        sale_price: 1499,
        category: "muffler",
        image: "/images/products/muffler-wool.png",
        image_url: "/images/products/muffler-wool.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 10,
        name: "Striped Woolen Muffler",
        description: "Stylish striped woolen muffler with contemporary design. Warm and comfortable, ideal for everyday winter wear.",
        price: 1499,
        salePrice: 999,
        sale_price: 999,
        category: "muffler",
        image: "/images/products/muffler-striped.png",
        image_url: "/images/products/muffler-striped.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },
    {
        id: 11,
        name: "Chunky Knit Winter Muffler",
        description: "Thick chunky knit muffler for extreme cold. Extra long for versatile styling. Cozy and fashionable.",
        price: 1799,
        salePrice: 1299,
        sale_price: 1299,
        category: "muffler",
        image: "/images/products/muffler-chunky.png",
        image_url: "/images/products/muffler-chunky.png",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },
    {
        id: 12,
        name: "Classic Winter Muffler - Brown",
        description: "Premium quality winter muffler in rich brown tone. Soft wool blend with elegant texture. Perfect for formal and casual winter outfits.",
        price: 1699,
        salePrice: 1299,
        sale_price: 1299,
        category: "muffler",
        image: "/images/products/WhatsApp Image 2025-12-26 at 8.49.59 PM.jpeg",
        image_url: "/images/products/WhatsApp Image 2025-12-26 at 8.49.59 PM.jpeg",
        sizes: ["One Size"],
        in_stock: true,
        featured: true,
    },
    {
        id: 13,
        name: "Classic Winter Muffler - Grey",
        description: "Elegant grey winter muffler with premium finish. Soft and warm, ideal for everyday winter wear. Pairs perfectly with any outfit.",
        price: 1699,
        salePrice: 1299,
        sale_price: 1299,
        category: "muffler",
        image: "/images/products/WhatsApp Image 2025-12-26 at 8.49.59 PM (1).jpeg",
        image_url: "/images/products/WhatsApp Image 2025-12-26 at 8.49.59 PM (1).jpeg",
        sizes: ["One Size"],
        in_stock: true,
        featured: false,
    },

    // ===== STITCHED SUITS (Women) =====
    {
        id: 14,
        name: "Banarsi Silk Stitched Suit",
        description: "Elegant Banarsi silk 3-piece stitched suit with intricate gold zari work. Includes shirt, trouser and dupatta. Perfect for Eid and weddings.",
        price: 15999,
        salePrice: 12999,
        sale_price: 12999,
        category: "suit-stitched",
        image: "/images/products/suit-banarsi.png",
        image_url: "/images/products/suit-banarsi.png",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 15,
        name: "Lawn Embroidered Suit",
        description: "Premium lawn fabric 3-piece suit with chiffon dupatta. Elegant embroidery on neckline and sleeves. Ready to wear for summer.",
        price: 7999,
        salePrice: 5999,
        sale_price: 5999,
        category: "suit-stitched",
        image: "/images/products/suit-lawn.png",
        image_url: "/images/products/suit-lawn.png",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 16,
        name: "Velvet Winter Suit",
        description: "Luxurious velvet 3-piece stitched suit with embroidered motifs. Warm and elegant for winter occasions. Includes matching shawl.",
        price: 18999,
        salePrice: 14999,
        sale_price: 14999,
        category: "suit-stitched",
        image: "/images/products/suit-velvet.png",
        image_url: "/images/products/suit-velvet.png",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },

    // ===== MEN'S STITCHED SUITS =====
    {
        id: 17,
        name: "Men's Premium Shalwar Kameez - White",
        description: "Classic white shalwar kameez for men. Made from premium cotton fabric with elegant stitching. Perfect for Eid, Friday prayers and formal occasions.",
        price: 4999,
        salePrice: 3999,
        sale_price: 3999,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.21 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.21 PM.jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 18,
        name: "Men's Designer Kurta - Embroidered",
        description: "Stylish embroidered kurta for men with intricate neckline design. Premium fabric with comfortable fit. Ideal for weddings and parties.",
        price: 5999,
        salePrice: 4499,
        sale_price: 4499,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.22 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.22 PM.jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 19,
        name: "Men's Formal Shalwar Kameez - Grey",
        description: "Elegant grey shalwar kameez with modern cut. Premium cotton blend fabric. Perfect for office and formal events.",
        price: 5499,
        salePrice: 4299,
        sale_price: 4299,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.23 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.23 PM.jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: false,
    },
    {
        id: 20,
        name: "Men's Traditional Kurta - Blue",
        description: "Classic blue kurta with traditional Pakistani design. Comfortable cotton fabric with side slits. Great for casual and semi-formal wear.",
        price: 4499,
        salePrice: 3499,
        sale_price: 3499,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.23 PM (1).jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.23 PM (1).jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: false,
    },
    {
        id: 21,
        name: "Men's Wedding Sherwani",
        description: "Luxurious wedding sherwani with heavy embroidery work. Includes matching trouser. Perfect for groom and wedding guests.",
        price: 25999,
        salePrice: 21999,
        sale_price: 21999,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.24 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.24 PM.jpeg",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 22,
        name: "Men's Festive Kurta - Black",
        description: "Stylish black kurta with subtle embroidery. Premium fabric with elegant finish. Perfect for Eid and festive occasions.",
        price: 5999,
        salePrice: 4799,
        sale_price: 4799,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.24 PM (1).jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.24 PM (1).jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: false,
    },
    {
        id: 23,
        name: "Men's Cotton Kurta - Casual",
        description: "Comfortable cotton kurta for everyday wear. Breathable fabric with relaxed fit. Available in multiple sizes.",
        price: 3499,
        salePrice: 2699,
        sale_price: 2699,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.25 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.25 PM.jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: false,
    },
    {
        id: 24,
        name: "Men's Premium Waistcoat Set",
        description: "Elegant waistcoat with matching kurta pajama. Perfect for weddings and formal events. Premium fabric with detailed embroidery.",
        price: 12999,
        salePrice: 9999,
        sale_price: 9999,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.49 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.49 PM.jpeg",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 25,
        name: "Men's Luxury Sherwani - Gold",
        description: "Royal gold sherwani with intricate embroidery. Includes matching churidar. The perfect choice for grooms.",
        price: 35999,
        salePrice: 29999,
        sale_price: 29999,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.49 PM (1).jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.49 PM (1).jpeg",
        sizes: ["S", "M", "L", "XL"],
        in_stock: true,
        featured: true,
    },
    {
        id: 26,
        name: "Men's Simple Kurta - Everyday",
        description: "Simple and elegant kurta for daily wear. Soft cotton fabric with comfortable fit. Easy to maintain and durable.",
        price: 2999,
        salePrice: 2299,
        sale_price: 2299,
        category: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.50 PM.jpeg",
        image_url: "/images/products/men/WhatsApp Image 2025-12-26 at 8.56.50 PM.jpeg",
        sizes: ["S", "M", "L", "XL", "XXL"],
        in_stock: true,
        featured: false,
    },

    // ===== UNSTITCHED SUITS =====
    {
        id: 27,
        name: "Khaddar Unstitched 3-Piece",
        description: "Premium khaddar unstitched fabric 3-piece suit. Includes 2.5m shirt, 2.5m trouser and 2.5m dupatta. Perfect for winter.",
        price: 4999,
        salePrice: 3999,
        sale_price: 3999,
        category: "suit-unstitched",
        image: "/images/products/suit-unstitched.png",
        image_url: "/images/products/suit-unstitched.png",
        sizes: ["Unstitched"],
        in_stock: true,
        featured: true,
    },
    {
        id: 28,
        name: "Lawn Digital Print Unstitched",
        description: "Premium lawn digital print unstitched suit with chiffon dupatta. Contemporary designs perfect for summer season.",
        price: 3999,
        salePrice: 2999,
        sale_price: 2999,
        category: "suit-unstitched",
        image: "/images/products/suit-stitched.png",
        image_url: "/images/products/suit-stitched.png",
        sizes: ["Unstitched"],
        in_stock: true,
        featured: false,
    },
    {
        id: 29,
        name: "Embroidered Chiffon Unstitched",
        description: "Luxury embroidered chiffon unstitched 3-piece. Heavy embroidery with handwork. Ideal for festive occasions.",
        price: 12999,
        salePrice: 9999,
        sale_price: 9999,
        category: "suit-unstitched",
        image: "/images/products/suit-banarsi.png",
        image_url: "/images/products/suit-banarsi.png",
        sizes: ["Unstitched"],
        in_stock: true,
        featured: true,
    },
];

// Collections/Categories with updated counts
export const collections = [
    {
        id: 1,
        name: "Shawls",
        slug: "shawl",
        image: "/images/products/shawl-white.png",
        count: 8,
        description: "Premium Wool Winter Shawls",
    },
    {
        id: 2,
        name: "Mufflers",
        slug: "muffler",
        image: "/images/products/muffler-wool.png",
        count: 5,
        description: "Warm Winter Mufflers",
    },
    {
        id: 3,
        name: "Stitched Suits",
        slug: "suit-stitched",
        image: "/images/products/suit-banarsi.png",
        count: 3,
        description: "Ready-to-Wear Women's Suits",
    },
    {
        id: 4,
        name: "Men's Stitched",
        slug: "men-stitched",
        image: "/images/products/men/WhatsApp Image 2025-12-26 at 8.54.21 PM.jpeg",
        count: 10,
        description: "Men's Shalwar Kameez & Sherwani",
    },
    {
        id: 5,
        name: "Unstitched Suits",
        slug: "suit-unstitched",
        image: "/images/products/suit-unstitched.png",
        count: 3,
        description: "Premium Unstitched Fabric",
    },
];

// Export products with normalized fields for frontend
export const products = staticProducts.map(p => ({
    ...p,
    image: p.image || p.image_url,
    salePrice: p.salePrice || p.sale_price,
}));

// Get product by ID
export function getProductById(id) {
    return products.find(p => p.id === parseInt(id));
}

// Get products by category
export function getProductsByCategory(category) {
    return products.filter(p => p.category === category);
}

// Get featured products
export function getFeaturedProducts() {
    return products.filter(p => p.featured);
}

// Get collection by slug
export function getCollectionBySlug(slug) {
    return collections.find(c => c.slug === slug);
}
