// Product data for the store - Pakistani Fashion Collection
// All prices in PKR (Pakistani Rupees)

export const staticProducts = [
    // ============================================
    // SCARVES COLLECTION
    // ============================================
    {
        id: 1,
        name: "Black & White Checkered Wool Scarf",
        sku: "25WSF010-00A-BWH",
        description: "Men & Women Casual Checkered Woolen Muffler Scarf. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/1st.jpeg",
        featured: true,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Black & White",
    },
    {
        id: 2,
        name: "Khaki Plain Wool Scarf",
        sku: "25WSF012-00A-KHK",
        description: "A khaki colored wool scarf with a soft feel and a simple plain finish. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/2nd.jpeg",
        featured: true,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Khaki",
    },
    {
        id: 3,
        name: "Black Plain Wool Scarf",
        sku: "25WSF012-00A-BLK",
        description: "A black wool scarf with a soft feel and a simple plain finish. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/3rd.jpeg",
        featured: true,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Black",
    },
    {
        id: 4,
        name: "Black Striped Wool Scarf",
        sku: "25WSF014-00A-BLK",
        description: "A black wool scarf with a contrast striped pattern and fringed edges. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/4th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Black",
    },
    {
        id: 5,
        name: "Khaki Tartan Wool Scarf",
        sku: "25WSF011-00A-KHK",
        description: "Khaki colored wool scarf in a classic tartan pattern, finished with soft fringed edges. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/5th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Khaki",
    },
    {
        id: 6,
        name: "Brown Tartan Wool Scarf",
        sku: "25WSF011-00A-BRO",
        description: "Brown wool scarf in a classic tartan pattern, finished with soft fringed edges. Wool + Cotton Blend.\n\nCARE:\n• Machine or handwash up to 30°C/86F\n• Gentle cycle\n• Do not dry in direct sunlight\n• Do not bleach\n• Do not iron directly on prints/embroidery\n\nActual colour of the product may vary slightly due to photographic lighting sources or your device.",
        price: 2000,
        salePrice: 1299,
        category: "scarves",
        image: "/images/products/scarves/6th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool + Cotton Blend",
        color: "Brown",
    },

    // ============================================
    // SHAWLS COLLECTION
    // ============================================
    {
        id: 7,
        name: "Brown Jacquard Wool Shawl",
        sku: "25SHL001-00A-BRO",
        description: "Colour: Brown\n\nWrap yourself in sophistication with this Jacquard Self Design Wool Shawl, crafted from premium soft wool to provide warmth, comfort, and timeless style. The elegant jacquard weave features a subtle self-design pattern that adds depth and refined texture. Perfect for chilly evenings or special occasions, this shawl enhances any outfit with a touch of luxury and grace.\n\nSize & Fit:\n• Free Size – Suitable for all\n• Standard Length Shawl\n\nSpecifications:\n• Type: Jacquard Self Design Wool Shawl\n• Design: Self Jacquard Pattern\n• Texture: Soft & Warm Finish\n• Occasion: Formal / Semi Formal\n\nCARE:\n• Dry Clean Recommended\n• Do Not Bleach\n• Do Not Tumble Dry\n• Iron on Low Heat if Needed",
        price: 4599,
        salePrice: 3299,
        category: "shawls",
        image: "/images/products/shawls/1st.jpeg",
        featured: true,
        inStock: true,
        material: "60% Pashmina Wool, 40% Acrylic",
        color: "Brown",
    },
    {
        id: 8,
        name: "Off-White Plain Shawl",
        sku: "25SHL002-00A-OWH",
        description: "Colour: Off-White\n\nWrap yourself in timeless elegance with our Plain Shawl, crafted from premium soft fabric for unbeatable comfort and warmth. The classic plain design adds a touch of sophistication, making it the perfect accessory for both casual and formal looks.\n\nSize & Fit:\n• Free Size – Suitable for all\n• Standard Length Shawl\n\nSpecifications:\n• Type: Plain Shawl\n• Design: Solid Plain\n• Texture: Soft & Warm\n• Occasion: Casual / Formal\n\nCARE:\n• Machine Wash\n• Do Not Bleach\n• Do Not Tumble Dry\n• Iron on Low Heat if Needed",
        price: 4599,
        salePrice: 3299,
        category: "shawls",
        image: "/images/products/shawls/2nd.jpeg",
        featured: true,
        inStock: true,
        material: "100% Acrylic",
        color: "Off-White",
    },
    {
        id: 9,
        name: "Light Brown Plain Shawl",
        sku: "25SHL002-00A-LBR",
        description: "Colour: Light Brown\n\nWrap yourself in timeless elegance with our Plain Shawl, crafted from premium soft fabric for unbeatable comfort and warmth. The classic plain design adds a touch of sophistication, making it the perfect accessory for both casual and formal looks.\n\nSize & Fit:\n• Free Size – Suitable for all\n• Standard Length Shawl\n\nSpecifications:\n• Type: Plain Shawl\n• Design: Solid Plain\n• Texture: Soft & Warm\n• Occasion: Casual / Formal\n\nCARE:\n• Machine Wash\n• Do Not Bleach\n• Do Not Tumble Dry\n• Iron on Low Heat if Needed",
        price: 4599,
        salePrice: 3299,
        category: "shawls",
        image: "/images/products/shawls/3rd.jpeg",
        featured: true,
        inStock: true,
        material: "100% Acrylic",
        color: "Light Brown",
    },
    {
        id: 10,
        name: "Grey Plain Shawl",
        sku: "25SHL002-00A-GRY",
        description: "Colour: Grey\n\nWrap yourself in timeless elegance with our Plain Shawl, crafted from premium soft fabric for unbeatable comfort and warmth. The classic plain design adds a touch of sophistication, making it the perfect accessory for both casual and formal looks.\n\nSize & Fit:\n• Free Size – Suitable for all\n• Standard Length Shawl\n\nSpecifications:\n• Type: Plain Shawl\n• Design: Solid Plain\n• Texture: Soft & Warm\n• Occasion: Casual / Formal\n\nCARE:\n• Machine Wash\n• Do Not Bleach\n• Do Not Tumble Dry\n• Iron on Low Heat if Needed",
        price: 4599,
        salePrice: 3299,
        category: "shawls",
        image: "/images/products/shawls/4th.jpeg",
        featured: false,
        inStock: true,
        material: "100% Acrylic",
        color: "Grey",
    },
    {
        id: 11,
        name: "Black Plain Shawl",
        sku: "25SHL002-00A-BLK",
        description: "Colour: Black\n\nWrap yourself in timeless elegance with our Plain Shawl, crafted from premium soft fabric for unbeatable comfort and warmth. The classic plain design adds a touch of sophistication, making it the perfect accessory for both casual and formal looks.\n\nSize & Fit:\n• Free Size – Suitable for all\n• Standard Length Shawl\n\nSpecifications:\n• Type: Plain Shawl\n• Design: Solid Plain\n• Texture: Soft & Warm\n• Occasion: Casual / Formal\n\nCARE:\n• Machine Wash\n• Do Not Bleach\n• Do Not Tumble Dry\n• Iron on Low Heat if Needed",
        price: 4599,
        salePrice: 3299,
        category: "shawls",
        image: "/images/products/shawls/5th.jpeg",
        featured: false,
        inStock: true,
        material: "100% Acrylic",
        color: "Black",
    },

    // ============================================
    // MEN'S UNSTITCHED COLLECTION
    // ============================================
    // Khaddar Suits (1-4)
    {
        id: 12,
        name: "Blue Khaddar Unstitched Suit",
        sku: "25MEN001-00A-BLU",
        description: "Premium Khaddar Unstitched Suit for Men\n\nDetails:\n• Fabric: Khaddar\n• Pattern: Plain\n• Season: Winter\n• Color: Blue\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 3199,
        category: "men-unstitched",
        image: "/images/products/mens/1st.jpeg",
        featured: true,
        inStock: true,
        material: "Khaddar",
        color: "Blue",
    },
    {
        id: 13,
        name: "Brown Khaddar Unstitched Suit",
        sku: "25MEN001-00A-BRO",
        description: "Premium Khaddar Unstitched Suit for Men\n\nDetails:\n• Fabric: Khaddar\n• Pattern: Plain\n• Season: Winter\n• Color: Brown\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 3199,
        category: "men-unstitched",
        image: "/images/products/mens/2nd.jpeg",
        featured: true,
        inStock: true,
        material: "Khaddar",
        color: "Brown",
    },
    {
        id: 14,
        name: "Black Khaddar Unstitched Suit",
        sku: "25MEN001-00A-BLK",
        description: "Premium Khaddar Unstitched Suit for Men\n\nDetails:\n• Fabric: Khaddar\n• Pattern: Plain\n• Season: Winter\n• Color: Black\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 3199,
        category: "men-unstitched",
        image: "/images/products/mens/3rd.jpeg",
        featured: true,
        inStock: true,
        material: "Khaddar",
        color: "Black",
    },
    {
        id: 15,
        name: "White Khaddar Unstitched Suit",
        sku: "25MEN001-00A-WHT",
        description: "Premium Khaddar Unstitched Suit for Men\n\nDetails:\n• Fabric: Khaddar\n• Pattern: Plain\n• Season: Winter\n• Color: White\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 3199,
        category: "men-unstitched",
        image: "/images/products/mens/4th.jpeg",
        featured: false,
        inStock: true,
        material: "Khaddar",
        color: "White",
    },
    // Wool Suits (5-8)
    {
        id: 16,
        name: "Grey Wool Unstitched Suit",
        sku: "25MEN002-00A-GRY",
        description: "Premium Wool Unstitched Suit for Men\n\nDetails:\n• Fabric: Wool\n• Pattern: Plain\n• Season: All Season\n• Color: Grey\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 6500,
        salePrice: 4599,
        category: "men-unstitched",
        image: "/images/products/mens/5th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool",
        color: "Grey",
    },
    {
        id: 17,
        name: "Black Wool Unstitched Suit",
        sku: "25MEN002-00A-BLK",
        description: "Premium Wool Unstitched Suit for Men\n\nDetails:\n• Fabric: Wool\n• Pattern: Plain\n• Season: All Season\n• Color: Black\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 6500,
        salePrice: 4599,
        category: "men-unstitched",
        image: "/images/products/mens/6th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool",
        color: "Black",
    },
    {
        id: 18,
        name: "Almond Wool Unstitched Suit",
        sku: "25MEN002-00A-ALM",
        description: "Premium Wool Unstitched Suit for Men\n\nDetails:\n• Fabric: Wool\n• Pattern: Plain\n• Season: All Season\n• Color: Almond\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 6500,
        salePrice: 4599,
        category: "men-unstitched",
        image: "/images/products/mens/7th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool",
        color: "Almond",
    },
    {
        id: 19,
        name: "Off-White Wool Unstitched Suit",
        sku: "25MEN002-00A-OWH",
        description: "Premium Wool Unstitched Suit for Men\n\nDetails:\n• Fabric: Wool\n• Pattern: Plain\n• Season: All Season\n• Color: Off-White\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 6500,
        salePrice: 4599,
        category: "men-unstitched",
        image: "/images/products/mens/8th.jpeg",
        featured: false,
        inStock: true,
        material: "Wool",
        color: "Off-White",
    },
    // Premium Wash & Wear Suits (9-11)
    {
        id: 20,
        name: "Biscuit Wash & Wear Unstitched Suit",
        sku: "25MEN003-00A-BIS",
        description: "Premium Wash & Wear Unstitched Suit for Men\n\nDetails:\n• Fabric: Premium Wash & Wear\n• Pattern: Plain\n• Season: All Season\n• Color: Biscuit\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 2799,
        category: "men-unstitched",
        image: "/images/products/mens/9th.jpeg",
        featured: false,
        inStock: true,
        material: "Premium Wash & Wear",
        color: "Biscuit",
    },
    {
        id: 21,
        name: "Skin Wash & Wear Unstitched Suit",
        sku: "25MEN003-00A-SKN",
        description: "Premium Wash & Wear Unstitched Suit for Men\n\nDetails:\n• Fabric: Premium Wash & Wear\n• Pattern: Plain\n• Season: All Season\n• Color: Skin\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 2799,
        category: "men-unstitched",
        image: "/images/products/mens/10th.jpeg",
        featured: false,
        inStock: true,
        material: "Premium Wash & Wear",
        color: "Skin",
    },
    {
        id: 22,
        name: "Off-White Wash & Wear Unstitched Suit",
        sku: "25MEN003-00A-OWH",
        description: "Premium Wash & Wear Unstitched Suit for Men\n\nDetails:\n• Fabric: Premium Wash & Wear\n• Pattern: Plain\n• Season: All Season\n• Color: Off-White\n• Accessories: Bag Included\n• Shirt Cutting: 2 Meter\n• Trouser Cutting: 2 Meter\n• Suit Cutting: 4 Meter\n• Package Includes: 1 x Suit\n• Condition: New\n\nNote: There might be an error of 1-3 cm due to manual measurement, and slight color differences may occur as a result of varying lighting and monitor effects.",
        price: 4500,
        salePrice: 2799,
        category: "men-unstitched",
        image: "/images/products/mens/11th.jpeg",
        featured: false,
        inStock: true,
        material: "Premium Wash & Wear",
        color: "Off-White",
    },
];

// Get all products (static for now, can be extended to fetch from database)
export const products = staticProducts;

// Get product by ID
export const getProductById = (id) => {
    return products.find(product => product.id === parseInt(id));
};

// Get products by category
export const getProductsByCategory = (category) => {
    return products.filter(product => product.category === category);
};

// Get featured products
export const getFeaturedProducts = () => {
    return products.filter(product => product.featured);
};

// Categories for the store - Only 3 categories
export const categories = [
    {
        id: 1,
        name: "Men's Unstitched",
        slug: "men-unstitched",
        image: "/images/categories/men-unstitched.jpg",
        count: 11,
        description: "Premium Unstitched Fabric for Men",
    },
    {
        id: 2,
        name: "Shawls",
        slug: "shawls",
        image: "/images/categories/shawls.jpg",
        count: 5,
        description: "Elegant Winter Shawls",
    },
    {
        id: 3,
        name: "Scarves",
        slug: "scarves",
        image: "/images/categories/scarves.jpg",
        count: 6,
        description: "Stylish Scarves Collection",
    },
];

// Get category by slug
export const getCategoryBySlug = (slug) => {
    return categories.find(cat => cat.slug === slug);
};

// Alias exports for backwards compatibility
export const collections = categories;
export const getCollectionBySlug = getCategoryBySlug;
